print('Привіт ви потрапели в гру Mad Libs\n')
print()
name = input("Введи ім'я персонажа: ")
place = input("Введи назву місця")
animal = input("Введи любу тварину ")
weapon = input("Введи зброю: ")
verb = input("Введи дію (дієслово): ")
print()
print(f"Одного разу {name} пішов у {place}, щоб знайти чарівного {animal}")
print("В руках він тримав {weapon}, готовий {verb} будь-кого, хто стане на заваді.")
print("Це була епічна пригода!")
print()
print("ось ваша історія")